{ config, lib, pkgs, ... }:

let
  # pywalfox-native ships only a manifest template (path = "<path>"); running
  # `pywalfox install` imperatively baked a store path into
  # ~/.mozilla/native-messaging-hosts/pywalfox.json that GC later deleted,
  # breaking the native messenger. This wrapper ships a proper manifest
  # pointing at the stable package path, fed to firefox.nativeMessagingHosts
  # so home-manager installs it declaratively (never goes stale).
  pywalfox-messaging-host = pkgs.runCommandLocal "pywalfox-messaging-host" { } ''
    mkdir -p $out/lib/mozilla/native-messaging-hosts
    cat > $out/lib/mozilla/native-messaging-hosts/pywalfox.json <<EOF
    {
      "name": "pywalfox",
      "description": "Automatically theme your browser using the colors generated by Pywal",
      "path": "${pkgs.pywalfox-native}/bin/pywalfox",
      "type": "stdio",
      "allowed_extensions": [ "pywalfox@frewacom.org" ]
    }
    EOF
  '';
in
{
  programs.firefox = {
    enable = true;
    package = pkgs.firefox-devedition;
    configPath = ".mozilla/firefox";
    nativeMessagingHosts = [ pywalfox-messaging-host ];
  };

  home.packages = [ pkgs.pywalfox-native ];
}
