[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.hyprland]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/hyprland-colors.conf'
output_path = '/home/rafael/.dotfiles/home/programs/hypr/colors.conf'

[templates.hyprlock]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/hyprlock-colors.conf'
output_path = '/home/rafael/.dotfiles/home/programs/hyprlock/colors.conf'

[templates.waybar]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/waybar-colors.css'
output_path = '/home/rafael/.dotfiles/home/programs/waybar/waybar-colors.css'

[templates.hyprlust-waybar]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/hyprlust_waybar.css'
output_path = '/home/rafael/.dotfiles/home/programs/waybar/hyprlust/waybar-colors.css'

[templates.wlogout]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/waybar-colors.css'
output_path = '/home/rafael/.config/wlogout/wlogout-colors.css'

[templates.kitty]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/kitty-colors.conf'
output_path = '/home/rafael/.dotfiles/home/programs/kitty/colors.conf'

[templates.rofi]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/rofi-colors.rasi'
output_path = '/home/rafael/.config/rofi/matugen-colors.rasi'

[templates.midnight-discord]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/midnight-discord.css'
output_path = '/home/rafael/.dotfiles/home/programs/nixcord/themes/midnight-colors.css'

[templates.pywalfox-colors]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/pywalfox-colors.json'
output_path = '/home/rafael/.cache/wal/colors.json'

[templates.gtk3]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/gtk-colors.css'
output_path = '/home/rafael/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/gtk-colors.css'
output_path = '/home/rafael/.config/gtk-4.0/colors.css'

[templates.qt]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/Matugen.colors'
output_path = '/home/rafael/.local/share/color-schemes/Matugen.colors'

[templates.spicetify]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/spotify-colors.ini'
output_path = '/home/rafael/.dotfiles/home/programs/spicetify/Themes/Comfy/color.ini'

[templates.btop]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.vesktop]
input_path = '/home/rafael/.dotfiles/home/programs/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[kvantum]
apply = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
