#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = efdee0
subtext            = d6c2c4
main               = 191113
main-elevated      = 413738
main-transition    = 140c0e
highlight          = 22191b
highlight-elevated = 3c3234
sidebar            = 191113
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = efdee0
button             = ffb1c1
button-active      = ffd9df
button-disabled    = ffb1c1
tab-active         = 191113
notification       = ecbe91
notification-error = ffb4ab
misc               = 000000
play-button        = e4bdc3
play-button-active = ffd9df
progress-fg        = ffb1c1
progress-bg        = 191113
heart              = ffb4ab
pagelink-active    = ffdcbd
radio-btn-active   = ffdcbd
