#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = f1dfdb
subtext            = d8c2bd
main               = 1a110f
main-elevated      = 423734
main-transition    = 140c0a
highlight          = 231917
highlight-elevated = 3d3230
sidebar            = 1a110f
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = f1dfdb
button             = ffb4a3
button-active      = ffdad2
button-disabled    = ffb4a3
tab-active         = 1a110f
notification       = dbc58c
notification-error = ffb4ab
misc               = 000000
play-button        = e7bdb3
play-button-active = ffdad2
progress-fg        = ffb4a3
progress-bg        = 1a110f
heart              = ffb4ab
pagelink-active    = f8e1a6
radio-btn-active   = f8e1a6
