#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = e6e0e9
subtext            = cac4cf
main               = 141218
main-elevated      = 3b383e
main-transition    = 0f0d13
highlight          = 1d1b20
highlight-elevated = 36343a
sidebar            = 141218
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = e6e0e9
button             = d0bcfe
button-active      = e9ddff
button-disabled    = d0bcfe
tab-active         = 141218
notification       = f0b8c7
notification-error = ffb4ab
misc               = 000000
play-button        = ccc2db
play-button-active = e8def8
progress-fg        = d0bcfe
progress-bg        = 141218
heart              = ffb4ab
pagelink-active    = ffd9e2
radio-btn-active   = ffd9e2
