$image = /home/rafael/Pictures/Wallpapers/orangci-walls/pink-clouds.jpg


$background = rgba(25, 17, 19, 1.0)

$blue = rgba(206, 189, 254, 1.0)

$blue_container = rgba(76, 62, 118, 1.0)

$blue_source = rgba(0, 0, 255, 1.0)

$blue_value = rgba(0, 0, 255, 1.0)

$cyan = rgba(130, 211, 226, 1.0)

$cyan_container = rgba(0, 78, 89, 1.0)

$cyan_source = rgba(0, 255, 255, 1.0)

$cyan_value = rgba(0, 255, 255, 1.0)

$error = rgba(255, 180, 171, 1.0)

$error_container = rgba(147, 0, 10, 1.0)

$green = rgba(183, 208, 133, 1.0)

$green_container = rgba(58, 77, 16, 1.0)

$green_source = rgba(0, 255, 0, 1.0)

$green_value = rgba(0, 255, 0, 1.0)

$inverse_on_surface = rgba(56, 46, 48, 1.0)

$inverse_primary = rgba(141, 74, 90, 1.0)

$inverse_surface = rgba(239, 222, 224, 1.0)

$magenta = rgba(252, 176, 213, 1.0)

$magenta_container = rgba(108, 51, 83, 1.0)

$magenta_source = rgba(255, 0, 255, 1.0)

$magenta_value = rgba(255, 0, 255, 1.0)

$on_background = rgba(239, 222, 224, 1.0)

$on_blue = rgba(53, 39, 94, 1.0)

$on_blue_container = rgba(232, 221, 255, 1.0)

$on_cyan = rgba(0, 54, 62, 1.0)

$on_cyan_container = rgba(158, 239, 255, 1.0)

$on_error = rgba(105, 0, 5, 1.0)

$on_error_container = rgba(255, 218, 214, 1.0)

$on_green = rgba(37, 54, 0, 1.0)

$on_green_container = rgba(211, 236, 158, 1.0)

$on_magenta = rgba(82, 29, 60, 1.0)

$on_magenta_container = rgba(255, 216, 232, 1.0)

$on_primary = rgba(85, 29, 45, 1.0)

$on_primary_container = rgba(255, 217, 223, 1.0)

$on_primary_fixed = rgba(58, 7, 24, 1.0)

$on_primary_fixed_variant = rgba(113, 51, 67, 1.0)

$on_red = rgba(86, 29, 34, 1.0)

$on_red_container = rgba(255, 218, 218, 1.0)

$on_secondary = rgba(67, 41, 47, 1.0)

$on_secondary_container = rgba(255, 217, 223, 1.0)

$on_secondary_fixed = rgba(43, 21, 26, 1.0)

$on_secondary_fixed_variant = rgba(91, 63, 69, 1.0)

$on_surface = rgba(239, 222, 224, 1.0)

$on_surface_variant = rgba(214, 194, 196, 1.0)

$on_tertiary = rgba(70, 42, 9, 1.0)

$on_tertiary_container = rgba(255, 220, 189, 1.0)

$on_tertiary_fixed = rgba(44, 22, 0, 1.0)

$on_tertiary_fixed_variant = rgba(96, 64, 29, 1.0)

$on_white = rgba(0, 54, 61, 1.0)

$on_white_container = rgba(158, 239, 253, 1.0)

$on_yellow = rgba(59, 47, 0, 1.0)

$on_yellow_container = rgba(252, 225, 134, 1.0)

$outline = rgba(158, 140, 143, 1.0)

$outline_variant = rgba(82, 67, 70, 1.0)

$primary = rgba(255, 177, 193, 1.0)

$primary_container = rgba(113, 51, 67, 1.0)

$primary_fixed = rgba(255, 217, 223, 1.0)

$primary_fixed_dim = rgba(255, 177, 193, 1.0)

$red = rgba(255, 179, 180, 1.0)

$red_container = rgba(115, 51, 55, 1.0)

$red_source = rgba(255, 0, 0, 1.0)

$red_value = rgba(255, 0, 0, 1.0)

$scrim = rgba(0, 0, 0, 1.0)

$secondary = rgba(228, 189, 195, 1.0)

$secondary_container = rgba(91, 63, 69, 1.0)

$secondary_fixed = rgba(255, 217, 223, 1.0)

$secondary_fixed_dim = rgba(228, 189, 195, 1.0)

$shadow = rgba(0, 0, 0, 1.0)

$source_color = rgba(250, 123, 156, 1.0)

$surface = rgba(25, 17, 19, 1.0)

$surface_bright = rgba(65, 55, 56, 1.0)

$surface_container = rgba(38, 29, 31, 1.0)

$surface_container_high = rgba(49, 40, 41, 1.0)

$surface_container_highest = rgba(60, 50, 52, 1.0)

$surface_container_low = rgba(34, 25, 27, 1.0)

$surface_container_lowest = rgba(20, 12, 14, 1.0)

$surface_dim = rgba(25, 17, 19, 1.0)

$surface_tint = rgba(255, 177, 193, 1.0)

$surface_variant = rgba(82, 67, 70, 1.0)

$tertiary = rgba(236, 190, 145, 1.0)

$tertiary_container = rgba(96, 64, 29, 1.0)

$tertiary_fixed = rgba(255, 220, 189, 1.0)

$tertiary_fixed_dim = rgba(236, 190, 145, 1.0)

$white = rgba(130, 211, 224, 1.0)

$white_container = rgba(0, 79, 88, 1.0)

$white_source = rgba(255, 255, 255, 1.0)

$white_value = rgba(255, 255, 255, 1.0)

$yellow = rgba(222, 197, 110, 1.0)

$yellow_container = rgba(85, 69, 0, 1.0)

$yellow_source = rgba(255, 255, 0, 1.0)

$yellow_value = rgba(255, 255, 0, 1.0)

