$image = /home/rafael/Pictures/Wallpapers/active/wallhaven-7j9wle.png


$background = 0xff141218

$blue = 0xffc7bfff

$blue_container = 0xff463f77

$blue_source = 0xff0000ff

$blue_value = 0xff0000ff

$cyan = 0xff82d3e2

$cyan_container = 0xff004e59

$cyan_source = 0xff00ffff

$cyan_value = 0xff00ffff

$error = 0xffffb4ab

$error_container = 0xff93000a

$green = 0xff95d5a7

$green_container = 0xff10512f

$green_source = 0xff00ff00

$green_value = 0xff00ff00

$inverse_on_surface = 0xff322f35

$inverse_primary = 0xff66558e

$inverse_surface = 0xffe6e0e9

$magenta = 0xffe4b7f3

$magenta_container = 0xff5c386b

$magenta_source = 0xffff00ff

$magenta_value = 0xffff00ff

$on_background = 0xffe6e0e9

$on_blue = 0xff2f285f

$on_blue_container = 0xffe5deff

$on_cyan = 0xff00363e

$on_cyan_container = 0xff9eefff

$on_error = 0xff690005

$on_error_container = 0xffffdad6

$on_green = 0xff00391d

$on_green_container = 0xffb0f1c2

$on_magenta = 0xff442253

$on_magenta_container = 0xfff7d8ff

$on_primary = 0xff37265d

$on_primary_container = 0xffe9ddff

$on_primary_fixed = 0xff210f47

$on_primary_fixed_variant = 0xff4e3d75

$on_red = 0xff561d26

$on_red_container = 0xffffdadc

$on_secondary = 0xff332d41

$on_secondary_container = 0xffe8def8

$on_secondary_fixed = 0xff1e192b

$on_secondary_fixed_variant = 0xff4a4458

$on_surface = 0xffe6e0e9

$on_surface_variant = 0xffcac4cf

$on_tertiary = 0xff4a2531

$on_tertiary_container = 0xffffd9e2

$on_tertiary_fixed = 0xff31101c

$on_tertiary_fixed_variant = 0xff633b48

$on_white = 0xff00363d

$on_white_container = 0xff9eeffd

$on_yellow = 0xff3b2f00

$on_yellow_container = 0xfffce186

$outline = 0xff948f99

$outline_variant = 0xff49454e

$primary = 0xffd0bcfe

$primary_container = 0xff4e3d75

$primary_fixed = 0xffe9ddff

$primary_fixed_dim = 0xffd0bcfe

$red = 0xffffb2b9

$red_container = 0xff72333b

$red_source = 0xffff0000

$red_value = 0xffff0000

$scrim = 0xff000000

$secondary = 0xffccc2db

$secondary_container = 0xff4a4458

$secondary_fixed = 0xffe8def8

$secondary_fixed_dim = 0xffccc2db

$shadow = 0xff000000

$source_color = 0xff7243d6

$surface = 0xff141218

$surface_bright = 0xff3b383e

$surface_container = 0xff211f24

$surface_container_high = 0xff2b292f

$surface_container_highest = 0xff36343a

$surface_container_low = 0xff1d1b20

$surface_container_lowest = 0xff0f0d13

$surface_dim = 0xff141218

$surface_tint = 0xffd0bcfe

$surface_variant = 0xff49454e

$tertiary = 0xfff0b8c7

$tertiary_container = 0xff633b48

$tertiary_fixed = 0xffffd9e2

$tertiary_fixed_dim = 0xfff0b8c7

$white = 0xff82d3e0

$white_container = 0xff004f58

$white_source = 0xffffffff

$white_value = 0xffffffff

$yellow = 0xffdec56e

$yellow_container = 0xff554500

$yellow_source = 0xffffff00

$yellow_value = 0xffffff00

