[palettes.matugen]
white = "{{colors.on_surface.default.hex}}"
blue = "{{colors.primary.default.hex}}"
green = "{{colors.green.default.hex}}"
red = "{{colors.error.default.hex}}"
yellow = "{{colors.yellow.default.hex}}"
magenta = "{{colors.magenta.default.hex}}"
cyan = "{{colors.cyan.default.hex}}"
purple = "{{colors.tertiary.default.hex}}"
bright-white = "{{colors.on_surface.default.hex}}"
bright-blue = "{{colors.primary_container.default.hex}}"
bright-green = "{{colors.green.default.hex}}"
bright-red = "{{colors.error.default.hex}}"
bright-yellow = "{{colors.tertiary.default.hex}}"
bright-cyan = "{{colors.secondary.default.hex}}"
bright-magenta = "{{colors.magenta.default.hex}}"
bright-purple = "{{colors.tertiary_container.default.hex}}"
