$image = Pictures/Wallpapers/orangci-walls/gingerbread-house.jpg


$background = 0xff1a110f

$error = 0xffffb4ab

$error_container = 0xff93000a

$inverse_on_surface = 0xff392e2c

$inverse_primary = 0xff904b3b

$inverse_surface = 0xfff1dfdb

$on_background = 0xfff1dfdb

$on_error = 0xff690005

$on_error_container = 0xffffdad6

$on_primary = 0xff561f12

$on_primary_container = 0xffffdad2

$on_primary_fixed = 0xff3a0a02

$on_primary_fixed_variant = 0xff723426

$on_secondary = 0xff442a23

$on_secondary_container = 0xffffdad2

$on_secondary_fixed = 0xff2c1510

$on_secondary_fixed_variant = 0xff5d3f39

$on_surface = 0xfff1dfdb

$on_surface_variant = 0xffd8c2bd

$on_tertiary = 0xff3c2f04

$on_tertiary_container = 0xfff8e1a6

$on_tertiary_fixed = 0xff241a00

$on_tertiary_fixed_variant = 0xff544519

$outline = 0xffa08c88

$outline_variant = 0xff534340

$primary = 0xffffb4a3

$primary_container = 0xff723426

$primary_fixed = 0xffffdad2

$primary_fixed_dim = 0xffffb4a3

$scrim = 0xff000000

$secondary = 0xffe7bdb3

$secondary_container = 0xff5d3f39

$secondary_fixed = 0xffffdad2

$secondary_fixed_dim = 0xffe7bdb3

$shadow = 0xff000000

$source_color = 0xffcc3b19

$surface = 0xff1a110f

$surface_bright = 0xff423734

$surface_container = 0xff271d1b

$surface_container_high = 0xff322825

$surface_container_highest = 0xff3d3230

$surface_container_low = 0xff231917

$surface_container_lowest = 0xff140c0a

$surface_dim = 0xff1a110f

$surface_tint = 0xffffb4a3

$surface_variant = 0xff534340

$tertiary = 0xffdbc58c

$tertiary_container = 0xff544519

$tertiary_fixed = 0xfff8e1a6

$tertiary_fixed_dim = 0xffdbc58c

