$image = Pictures/Wallpapers/orangci-walls/venice-market.png


$background = 0xff1a110e

$error = 0xffffb4ab

$error_container = 0xff93000a

$inverse_on_surface = 0xff392e2b

$inverse_primary = 0xff8f4c33

$inverse_surface = 0xfff1dfd9

$on_background = 0xfff1dfd9

$on_error = 0xff690005

$on_error_container = 0xffffdad6

$on_primary = 0xff55200a

$on_primary_container = 0xffffdbcf

$on_primary_fixed = 0xff380d00

$on_primary_fixed_variant = 0xff72361e

$on_secondary = 0xff442a21

$on_secondary_container = 0xffffdbcf

$on_secondary_fixed = 0xff2c160d

$on_secondary_fixed_variant = 0xff5d4035

$on_surface = 0xfff1dfd9

$on_surface_variant = 0xffd8c2bb

$on_tertiary = 0xff393005

$on_tertiary_container = 0xfff2e2a8

$on_tertiary_fixed = 0xff211b00

$on_tertiary_fixed_variant = 0xff50471a

$outline = 0xffa08d86

$outline_variant = 0xff53433e

$primary = 0xffffb59a

$primary_container = 0xff72361e

$primary_fixed = 0xffffdbcf

$primary_fixed_dim = 0xffffb59a

$scrim = 0xff000000

$secondary = 0xffe7beaf

$secondary_container = 0xff5d4035

$secondary_fixed = 0xffffdbcf

$secondary_fixed_dim = 0xffe7beaf

$shadow = 0xff000000

$source_color = 0xffdc6a3d

$surface = 0xff1a110e

$surface_bright = 0xff423733

$surface_container = 0xff271d1a

$surface_container_high = 0xff322824

$surface_container_highest = 0xff3d322f

$surface_container_low = 0xff231a16

$surface_container_lowest = 0xff140c09

$surface_dim = 0xff1a110e

$surface_tint = 0xffffb59a

$surface_variant = 0xff53433e

$tertiary = 0xffd5c68e

$tertiary_container = 0xff50471a

$tertiary_fixed = 0xfff2e2a8

$tertiary_fixed_dim = 0xffd5c68e

