$image = /home/rafael/Pictures/Wallpapers/active/wallhaven-yq769k.png


$background = 0xff19120d

$blue = 0xffcebdfe

$blue_container = 0xff4c3e76

$blue_source = 0xff0000ff

$blue_value = 0xff0000ff

$cyan = 0xff84d5c4

$cyan_container = 0xff005045

$cyan_source = 0xff00ffff

$cyan_value = 0xff00ffff

$error = 0xffffb4ab

$error_container = 0xff93000a

$green = 0xffb7d085

$green_container = 0xff3a4d10

$green_source = 0xff00ff00

$green_value = 0xff00ff00

$inverse_on_surface = 0xff382e29

$inverse_primary = 0xff8b4f24

$inverse_surface = 0xfff0dfd7

$magenta = 0xfffcb0d5

$magenta_container = 0xff6c3353

$magenta_source = 0xffff00ff

$magenta_value = 0xffff00ff

$on_background = 0xfff0dfd7

$on_blue = 0xff35275e

$on_blue_container = 0xffe8ddff

$on_cyan = 0xff00382f

$on_cyan_container = 0xff9ff2e0

$on_error = 0xff690005

$on_error_container = 0xffffdad6

$on_green = 0xff253600

$on_green_container = 0xffd3ec9e

$on_magenta = 0xff521d3c

$on_magenta_container = 0xffffd8e8

$on_primary = 0xff512400

$on_primary_container = 0xffffdbc7

$on_primary_fixed = 0xff311300

$on_primary_fixed_variant = 0xff6e380f

$on_red = 0xff552009

$on_red_container = 0xffffdbce

$on_secondary = 0xff432b1c

$on_secondary_container = 0xffffdbc7

$on_secondary_fixed = 0xff2b1709

$on_secondary_fixed_variant = 0xff5b4130

$on_surface = 0xfff0dfd7

$on_surface_variant = 0xffd7c3b8

$on_tertiary = 0xff32320a

$on_tertiary_container = 0xffe7e6ad

$on_tertiary_fixed = 0xff1c1d00

$on_tertiary_fixed_variant = 0xff48491e

$on_white = 0xff00363d

$on_white_container = 0xff9eeffd

$on_yellow = 0xff3b2f00

$on_yellow_container = 0xfffce186

$outline = 0xff9f8d83

$outline_variant = 0xff52443c

$primary = 0xffffb688

$primary_container = 0xff6e380f

$primary_fixed = 0xffffdbc7

$primary_fixed_dim = 0xffffb688

$red = 0xffffb599

$red_container = 0xff71361d

$red_source = 0xffff0000

$red_value = 0xffff0000

$scrim = 0xff000000

$secondary = 0xffe5bfa9

$secondary_container = 0xff5b4130

$secondary_fixed = 0xffffdbc7

$secondary_fixed_dim = 0xffe5bfa9

$shadow = 0xff000000

$source_color = 0xffc16212

$surface = 0xff19120d

$surface_bright = 0xff413731

$surface_container = 0xff261e19

$surface_container_high = 0xff312823

$surface_container_highest = 0xff3d332d

$surface_container_low = 0xff221a15

$surface_container_lowest = 0xff140d08

$surface_dim = 0xff19120d

$surface_tint = 0xffffb688

$surface_variant = 0xff52443c

$tertiary = 0xffcaca93

$tertiary_container = 0xff48491e

$tertiary_fixed = 0xffe7e6ad

$tertiary_fixed_dim = 0xffcaca93

$white = 0xff82d3e0

$white_container = 0xff004f58

$white_source = 0xffffffff

$white_value = 0xffffffff

$yellow = 0xffdec56e

$yellow_container = 0xff554500

$yellow_source = 0xffffff00

$yellow_value = 0xffffff00

