[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.hyprland]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/hyprland-colors.conf'
output_path = '/home/rafael/.dotfiles/home/config/hypr/colors.conf'

[templates.hyprlock]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/hyprlock-colors.conf'
output_path = '/home/rafael/.dotfiles/home/config/hyprlock/colors.conf'

[templates.waybar]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/waybar-colors.css'
output_path = '/home/rafael/.dotfiles/home/config/waybar/waybar-colors.css'

[templates.hyprlust-waybar]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/hyprlust_waybar.css'
output_path = '/home/rafael/.dotfiles/home/config/waybar/hyprlust/waybar-colors.css'

[templates.wlogout]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/waybar-colors.css'
output_path = '/home/rafael/.config/wlogout/wlogout-colors.css'

[templates.kitty]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/kitty-colors.conf'
output_path = '/home/rafael/.dotfiles/home/config/kitty/colors.conf'

[templates.rofi]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/rofi-colors.rasi'
output_path = '/home/rafael/.config/rofi/matugen-colors.rasi'

[templates.midnight-discord]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/midnight-discord.css'
output_path = '/home/rafael/.dotfiles/home/config/nixcord/themes/midnight-colors.css'

[templates.pywalfox-colors]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/pywalfox-colors.json'
output_path = '/home/rafael/.cache/wal/colors.json'

[templates.gtk3]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/gtk-colors.css'
output_path = '/home/rafael/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/gtk-colors.css'
output_path = '/home/rafael/.config/gtk-4.0/colors.css'

[templates.qt]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/qtct-colors.conf'
output_path = '/home/rafael/.config/qt6ct/colors/Matugen.conf'

[templates.qt2]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/Matugen.colors'
output_path = '/home/rafael/.local/share/color-schemes/Matugen.colors'

[templates.spicetify]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/spotify-colors.ini'
output_path = '/home/rafael/.dotfiles/home/config/spicetify/Themes/Comfy/color.ini'

[templates.starship]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/starship-colors.toml'
output_path = '/home/rafael/.cache/matugen/starship-palette.toml'
post_hook = "sed -i '/^palette = /d; /^\\[palettes\\./,$d' /home/rafael/.config/starship.toml && echo 'palette = \"matugen\"' >> /home/rafael/.config/starship.toml && cat /home/rafael/.cache/matugen/starship-palette.toml >> /home/rafael/.config/starship.toml"

[templates.kmscon]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/kmscon-colors.nix'
output_path = '/home/rafael/.dotfiles/home/config/matugen/generated/kmscon-palette.nix'

[templates.zellij]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/zellij-colors.kdl'
output_path = '/home/rafael/.config/zellij/themes/matugen.kdl'

[templates.btop]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.vesktop]
input_path = '/home/rafael/.dotfiles/home/config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

# [templates.nvim]
# input_path = '~/.config/nvim/pywal/matugen.lua'
# output_path = '~/.cache/wal/base46-dark.lua'
# post_hook = "~/.config/waypaper/wallpaper.sh"

[kvantum]
apply = true

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
